name: Publisher
on: 
    push:
        branches: ['main', 'master']

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[PUBLISHER]')
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
      length-files: ${{ steps.lg_out.outputs.lg_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo "# Building" >> $GITHUB_STEP_SUMMARY
      - name: get changed files
        uses: tj-actions/changed-files@v23
        id: changed-files
        with:
          separator: ";"
          quotepath: "false"
          since_last_remote_commit: true
      - name: set lg outputs
        id: lg_out
        run: |
          changed=${{ needs.build.outputs.all_changed_files }}
          lg_steps=${#changed}
          echo "::set-output name=lg_files::$lg_steps"
          echo "::set-output name=changed-files::$changed"
  installation: 
    runs-on: ubuntu-latest
    needs: [build]
    if:  needs.build.outputs.length-files > 0 
    steps:
      - name: Requirements
        run: |
          pip install obs2mk --upgrade
          pip install -r requirements.txt
      - name: generate markdown
        run: |
          echo "File processed:  " >> $GITHUB_STEP_SUMMARY
      - name: obs2mk source files
        run: |
          IFS=$';'
          changed="${{ needs.build.outputs.all_changed_files }}"
          for file in $changed; do
            if [[ "$file" == *md ]] 
              then
                echo "- $file " >> $GITHUB_STEP_SUMMARY
                obs2mk --minimal file "$file"
              fi
            done
          unset IFS
      - name: Mkdocs build
        run: |
          mkdocs gh-deploy --force --clean
      - name: Push updateds files
        run: |
          git pull
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          rm -rf ./site/
          git add . 
          fileList=$(git status --porcelain | tr -d '\n' | tr -d 'M' |tr -d '??')
          git commit -m "ðŸ“ Publishing from ObsidianMD" -m "${fileList}"
          git push
  sucess:
    runs-on: ubuntu-latest
    needs: [installation, build]
    if: always() && (needs.installation.result == 'failure')
    steps: 
      - name: Ending summary
        run: |
          echo "âš ï¸ Error during build!!!" >> $GITHUB_STEP_SUMMARY
  failure:
    runs-on: ubuntu-latest
    needs: [installation, build]
    if: always() && (needs.installation.result == 'success')
    steps:
      - name: ending summary
        run: |
          LINK=$(head -n 1 .github/.env)
          echo "ðŸŽ‰ Successfully converted files and build documentation" >> $GITHUB_STEP_SUMMARY
          echo "Your blog is successfully build at $LINK" >> $GITHUB_STEP_SUMMARY
  nothing:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.length-files == 0
    steps:
      - name: message
        run: |
          echo "${{ needs.build.outputs.all_changed_files }}"
          echo "ðŸ¤” Nothing to commit, ending" >> $GITHUB_STEP_SUMMARY 